### ISSUE TITLE
Make functional study structure import / export working with existing internal references

### ISSUE THREAD

**Issue by WorksofFaith** [MORE-Platform/more-studymanager-backend#191]
none of the interventions worked when importing an existing study configuration and starting a new one using that configuration (Devender)

**Comment by andresgruber** [comment]
We @drtyyj and @andresgruber investigated, whether and where there exists this reported bug.
- The structure for exporting and importing seems correct and complete.
- I've created a study with study groups and action notifications for one group and exported it and imported it again.

- So: We could not reproduce it this way.

Is there any specific study configuration, that you @alireza-dhp remember for this bug?

**Comment by alireza-dhp** [comment]
Dear @andresgruber,

I observed that the "action notification" and "trigger conditions" on the Intervention tab do not work properly on an imported study. 
It appears that the observation id is not properly set.
this the exported study file: [study_config_26.json](https://github.com/MORE-Platform/more-studymanager-backend/files/15025336/study_config_26.json)

The integration item does not import as well, which is not a major problem.since we have to redefine it in order to obtain a new token,

**Comment by andresgruber** [comment]
- Remove the LimeSurvey ID and add a "warning" to clone the LimeSurvey, so that the triggers would work again!

**Comment by alireza-dhp** [comment]
> * Remove the LimeSurvey ID and add a "warning" to clone the LimeSurvey, so that the triggers would work again!

Is the above comment missing in PR #251? (an imported study with an invalid limesurvey id does not start!)
My suggestion is showing a warning dialog and asking to clone the limesurvey(s) and update the coresponding limesurvey ID(s) before tackling #247.

**Comment by alireza-dhp** [comment]
We agreed to fix the limesurvey ID on #247. 
Currently, it simply causes the corresponding field on the limesurvey observation to become empty but does not display a pop-up message.
